spring.application.name=StockFolio

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.name=stockfolioJwt
jwt.cookie.expiration=3600

encrypt.key=${ENCRYPT_KEY}

oauthpassword=${OAUTH_PASSWORD}

google.redirect.uri=${GOOGLE_REDIRECT_URI}
google.client.key=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}

kakao.client_key=${KAKAO_CLIENT_KEY}
kakao.redirect.uri=${KAKAO_REDIRECT_URI}

mailgun.key=${MAILGUN_KEY}

coolsms.send_number=${COOLSMS_SEND_NUMBER}
coolsms.key=${COOLSMS_KEY}
coolsms.secret=${COOLSMS_SECRET}

external.fmp.api-key=${FMP_API_KEY}
external.krx.api-key=${KRX_API_KEY}
external.opendart.api-key=${OPENDART_API_KEY}
